import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    tutorialSidebar: ["intro", "usage", "architecture"],
    apiSidebar: [
        {
            type: "autogenerated",
            dirName: "types", // Unwrap API reference to avoid double nesting
        },
    ],
};

export default sidebars;
