import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
    tutorialSidebar: [
        {
            type: "autogenerated",
            dirName: ".", // Generates sidebar from the docs folder (root)
        },
    ],
    apiSidebar: [
        {
            type: "autogenerated",
            dirName: "types",
        },
    ],
};

export default sidebars;
